name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install modules
        run: npm install
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
